<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LoyaltyTier;
use App\Models\LoyaltyPointAction;

class LoyaltyDefaultDataSeeder extends Seeder
{
    public function run(): void
    {
        LoyaltyTier::truncate();
        LoyaltyPointAction::truncate();

        LoyaltyTier::insert([
            [
                'name' => 'POP Fan',
                'slug' => 'fan',
                'min_points' => 0,
                'max_points' => 499,
                'color' => '#9CA3AF',
                'bg_color' => '#374151',
                'border_color' => '#4B5563',
                'icon' => 'person',
                'benefits' => json_encode(['Promos básicas', 'Puntos por compra']),
                'config' => json_encode(['points_multiplier' => 1.0]),
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'POP Lover',
                'slug' => 'lover',
                'min_points' => 500,
                'max_points' => 1499,
                'color' => '#F2C894',
                'bg_color' => '#F2C894',
                'border_color' => '#F2C894',
                'icon' => 'favorite',
                'benefits' => json_encode(['+10% puntos', 'Promo mensual', 'Bebida gratis cumpleaños']),
                'config' => json_encode(['points_multiplier' => 1.1]),
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'POP VIP',
                'slug' => 'vip',
                'min_points' => 1500,
                'max_points' => 2999,
                'color' => '#D96725',
                'bg_color' => '#D96725',
                'border_color' => '#D96725',
                'icon' => 'workspace_premium',
                'benefits' => json_encode(['+25% puntos', 'Roll gratis c/5 visitas', 'Acceso anticipado']),
                'config' => json_encode(['points_multiplier' => 1.25]),
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'POP Elite',
                'slug' => 'elite',
                'min_points' => 3000,
                'max_points' => null,
                'color' => '#F2C777',
                'bg_color' => '#F2C777',
                'border_color' => '#F2C777',
                'icon' => 'military_tech',
                'benefits' => json_encode(['+50% puntos', 'Reservación prioritaria', '1 buffet gratis/mes', 'Eventos VIP']),
                'config' => json_encode(['points_multiplier' => 1.5]),
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        LoyaltyPointAction::insert([
            [
                'action' => 'Primer registro',
                'slug' => 'welcome',
                'points' => 50,
                'points_type' => 'fixed',
                'icon' => 'person_add',
                'color' => '#F2C777',
                'is_active' => true,
                'sort_order' => 1,
                'description' => 'Bono de bienvenida al registrarse',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Por cada $5 MXN gastados',
                'slug' => 'purchase',
                'points' => 1,
                'points_type' => 'per_amount',
                'icon' => 'payments',
                'color' => '#D96E30',
                'is_active' => true,
                'sort_order' => 1,
                'description' => 'En consumo dentro del restaurante o en tu pedido a domicilio.',
                'conditions' => json_encode(['amount' => 5]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Por check-in en restaurante',
                'slug' => 'checkin',
                'points' => 25,
                'points_type' => 'fixed',
                'icon' => 'location_on',
                'color' => '#34D399',
                'is_active' => true,
                'sort_order' => 3,
                'description' => 'Cada vez que visitas el local y registras tu entrada.',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Por referir un amigo',
                'slug' => 'referral',
                'points' => 200,
                'points_type' => 'fixed',
                'icon' => 'group_add',
                'color' => '#2DD4BF',
                'is_active' => true,
                'sort_order' => 4,
                'description' => 'Cuando tu amigo hace su primer pedido tras registrarse con tu referido.',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Por reseña en Google',
                'slug' => 'review',
                'points' => 100,
                'points_type' => 'fixed',
                'icon' => 'star',
                'color' => '#3B82F6',
                'is_active' => true,
                'sort_order' => 5,
                'description' => 'Deja una reseña con foto y recibe 100 puntos de bonificación.',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'En tu cumpleaños',
                'slug' => 'birthday',
                'points' => 150,
                'points_type' => 'fixed',
                'icon' => 'cake',
                'color' => '#A78BFA',
                'is_active' => true,
                'sort_order' => 6,
                'description' => 'Puntos automáticos cada año en tu fecha de cumpleaños registrada.',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Double Checkpoint',
                'slug' => 'double_checkpoint',
                'points' => 2,
                'points_type' => 'multiplier',
                'icon' => 'bolt',
                'color' => '#EF4444',
                'is_active' => true,
                'sort_order' => 7,
                'description' => 'Lunes y jueves son Double Checkpoint: el doble de puntos en ambos días. El jueves además coincide con Jueboneless — boneless al 2x1 Y el doble de puntos, todo en una sola visita.',
                'conditions' => json_encode(['multiplier' => 2, 'days' => ['monday', 'thursday']]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}