<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LoyaltyTier;
use App\Models\LoyaltyPointAction;

class LoyaltyDefaultDataSeeder extends Seeder
{
    public function run(): void
    {
        LoyaltyTier::truncate();
        LoyaltyPointAction::truncate();

        LoyaltyTier::insert([
            [
                'name' => 'POP Fan',
                'slug' => 'fan',
                'min_points' => 0,
                'max_points' => 499,
                'color' => '#9CA3AF',
                'bg_color' => '#374151',
                'border_color' => '#4B5563',
                'icon' => 'person',
                'benefits' => json_encode(['Promos básicas', 'Puntos por compra']),
                'config' => json_encode(['points_multiplier' => 1.0]),
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'POP Lover',
                'slug' => 'lover',
                'min_points' => 500,
                'max_points' => 1499,
                'color' => '#F2C894',
                'bg_color' => '#F2C894',
                'border_color' => '#F2C894',
                'icon' => 'favorite',
                'benefits' => json_encode(['+10% puntos', 'Promo mensual', 'Bebida gratis cumpleaños']),
                'config' => json_encode(['points_multiplier' => 1.1]),
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'POP VIP',
                'slug' => 'vip',
                'min_points' => 1500,
                'max_points' => 2999,
                'color' => '#D96725',
                'bg_color' => '#D96725',
                'border_color' => '#D96725',
                'icon' => 'workspace_premium',
                'benefits' => json_encode(['+25% puntos', 'Roll gratis c/5 visitas', 'Acceso anticipado']),
                'config' => json_encode(['points_multiplier' => 1.25]),
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'POP Elite',
                'slug' => 'elite',
                'min_points' => 3000,
                'max_points' => null,
                'color' => '#F2C777',
                'bg_color' => '#F2C777',
                'border_color' => '#F2C777',
                'icon' => 'military_tech',
                'benefits' => json_encode(['+50% puntos', 'Reservación prioritaria', '1 buffet gratis/mes', 'Eventos VIP']),
                'config' => json_encode(['points_multiplier' => 1.5]),
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        LoyaltyPointAction::insert([
            [
                'action' => 'Primer registro',
                'slug' => 'welcome',
                'points' => 50,
                'points_type' => 'fixed',
                'icon' => 'person_add',
                'color' => '#F2C777',
                'is_active' => true,
                'sort_order' => 1,
                'description' => 'Bono de bienvenida al registrarse',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Por cada $10 MXN',
                'slug' => 'purchase',
                'points' => 1,
                'points_type' => 'per_amount',
                'icon' => 'shopping_cart',
                'color' => '#F2C777',
                'is_active' => true,
                'sort_order' => 2,
                'description' => '1 punto por cada $10 MXN gastados',
                'conditions' => json_encode(['amount' => 10]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Check-in en restaurante',
                'slug' => 'checkin',
                'points' => 25,
                'points_type' => 'fixed',
                'icon' => 'location_on',
                'color' => '#F2C777',
                'is_active' => true,
                'sort_order' => 3,
                'description' => 'Puntos por visitar el restaurante',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Reseña Google',
                'slug' => 'review',
                'points' => 100,
                'points_type' => 'fixed',
                'icon' => 'star',
                'color' => '#F2C777',
                'is_active' => true,
                'sort_order' => 4,
                'description' => 'Puntos por dejar reseña con prueba',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Referir amigo',
                'slug' => 'referral',
                'points' => 200,
                'points_type' => 'fixed',
                'icon' => 'group_add',
                'color' => '#F2C777',
                'is_active' => true,
                'sort_order' => 5,
                'description' => 'Cuando el amigo hace su primer pedido',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Double Check',
                'slug' => 'low_traffic',
                'points' => 2,
                'points_type' => 'multiplier',
                'icon' => 'calendar_today',
                'color' => '#D96725',
                'is_active' => true,
                'sort_order' => 6,
                'description' => '2x puntos los lunes y jueves',
                'conditions' => json_encode(['multiplier' => 2]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Cumpleaños',
                'slug' => 'birthday',
                'points' => 150,
                'points_type' => 'fixed',
                'icon' => 'cake',
                'color' => '#F2C777',
                'is_active' => true,
                'sort_order' => 7,
                'description' => 'Puntos automáticos en cumpleaños',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'action' => 'Compartir en redes',
                'slug' => 'social_share',
                'points' => 30,
                'points_type' => 'fixed',
                'icon' => 'share',
                'color' => '#F2C777',
                'is_active' => true,
                'sort_order' => 8,
                'description' => 'Puntos por compartir en redes sociales',
                'conditions' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}